96boards/meta-rpb

- conf/distro/include/rpb.inc
> rbp: set DISTRO_VERSION to 2016.06

- recipes-samples/images/rpb-console-image.bb
- recipes-samples/images/rpb-desktop-image.bb
- recipes-samples/images/rpb-weston-image.bb
* tools-debug
* connmanctl
* hostapd and iptables
* gstreamer packages (on desktop and weston images only)
* aplay/arecord
> images: add tools-debug and a few utilities in reference images

- recipes-samples/images/rpb-console-image.bb
- recipes-samples/images/rpb-desktop-image.bb
- recipes-samples/images/rpb-weston-image.bb
> *image: add optee based on MACHINE_FEATURES

- recipes-samples/images/rpb-desktop-image.bb
> rpb-desktop-image: add glmark2

- conf/distro/rpb-wayland.conf
- recipes-samples/images/rpb-weston-image.bb
Changes vs previous version:
- rebased to the current master
- added FIXME to distro/rpb-wayland.conf and images/rpb-weston-image.bb
> Mali450 hikey v2

- recipes-samples/images/rpb-console-image-lava.bb
- recipes-samples/images/rpb-desktop-image-lava.bb
- recipes-samples/images/rpb-weston-image-lava.bb
> image recipe samples: add variants with LAVA deps included.

- recipes-samples/images/rpb-console-image.bb
- recipes-samples/images/rpb-desktop-image.bb
- recipes-samples/images/rpb-weston-image.bb
tested wifi with nmcli  on hikey and dragonboard-410c
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
> image recipe samples: use networkmanager instead of connman

- conf/distro/include/rpb.inc
Signed-off-by: Zoltan Kuscsik <kuscsik@gmail.com>
> rpb.inc: allow FFmpeg to be included in RPB builds

- conf/distro/include/rpb.inc
> rpb.inc: set TARGET_VENDOR to linaro

- conf/distro/include/egl.inc
- conf/distro/include/rpb.inc
- conf/distro/rpb-wayland.conf
- recipes-samples/images/rpb-weston-image.bb
Follow up on https://github.com/96boards/meta-rpb/pull/34
> Add powervr support v2

- conf/distro/include/rpb.inc
> rbp.inc: disable multilib till bugs are fixed

- conf/distro/include/rpb.inc
This adds the patch from morty to krogoth
> rbp.inc: disable multilib till bugs are fixes

- conf/distro/include/rpb.inc
> rpb: move to gcc linaro-6.2

- recipes-samples/images/rpb-console-image-lava.bb
- recipes-samples/images/rpb-desktop-image-lava.bb
- recipes-samples/images/rpb-weston-image-lava.bb
- recipes-samples/packagegroups/packagegroup-rpb-tests.bb
And since we are going to keep adding more packages, let's organize the test images with packagegroups..
> Added a few more packages needed for LAVA

- recipes-samples/images/rpb-console-image.bb
- recipes-samples/images/rpb-desktop-image.bb
- recipes-samples/images/rpb-weston-image.bb
> rpb-*-image: add glmark2, cpufrequtils and htop

- recipes-samples/images/rpb-desktop-image.bb
- recipes-samples/images/rpb-weston-image.bb
on graphical images, add linaro user to video group.
> rpb: add linaro user to video group

- recipes-samples/packagegroups/packagegroup-rpb.bb
> packagegroup-rpb: add docker

- recipes-samples/packagegroups/packagegroup-rpb.bb
> packagegroup: rpb: add rsync

- conf/distro/include/rpb.inc
same change as the one just merged into master
> rpb.inc: add ext4.gz image

- recipes-overlayed/efivar/efivar/0001-efivar-fix-for-cross-compile.patch
- recipes-overlayed/efivar/efivar/0003-efivar-fix-for-cross-compile.patch
- recipes-overlayed/efivar/efivar/allow-multi-definitions-for-native.patch
- recipes-overlayed/efivar/efivar_0.30.bb
Efivar doesn't build in morty either, so overlay it into here as well.
> Overlay efivar

- conf/distro/include/rpb.inc
'netperf' needs in and RPB isn't commercial.
> rpb: whitelist 'non-commercial' license

- recipes-overlayed/ltp/ltp/0001-add-_GNU_SOURCE-to-pec_listener.c.patch
- recipes-overlayed/ltp/ltp/0002-Add-knob-to-control-whether-numa-support-should-be-c.patch
- recipes-overlayed/ltp/ltp/0003-Add-knob-to-control-tirpc-support.patch
- recipes-overlayed/ltp/ltp/0004-build-Add-option-to-select-libc-implementation.patch
- recipes-overlayed/ltp/ltp/0005-kernel-controllers-Link-with-libfts-explicitly-on-mu.patch
- recipes-overlayed/ltp/ltp/0006-fix-PATH_MAX-undeclared-when-building-with-musl.patch
- recipes-overlayed/ltp/ltp/0007-fix-__WORDSIZE-undeclared-when-building-with-musl.patch
- recipes-overlayed/ltp/ltp/0008-Check-if-__GLIBC_PREREQ-is-defined-before-using-it.patch
- recipes-overlayed/ltp/ltp/0009-fix-redefinition-of-struct-msgbuf-error-building-wit.patch
- recipes-overlayed/ltp/ltp/0010-replace-__BEGIN_DECLS-and-__END_DECLS.patch
- recipes-overlayed/ltp/ltp/0011-Rename-sigset-variable-to-sigset1.patch
- recipes-overlayed/ltp/ltp/0012-fix-faccessat01.c-build-fails-with-security-flags.patch
- recipes-overlayed/ltp/ltp/0018-guard-mallocopt-with-__GLIBC__.patch
- recipes-overlayed/ltp/ltp/0020-getdents-define-getdents-getdents64-only-for-glibc.patch
- recipes-overlayed/ltp/ltp/0021-Define-_GNU_SOURCE-for-MREMAP_MAYMOVE-definition.patch
- recipes-overlayed/ltp/ltp/0023-ptrace-Use-int-instead-of-enum-__ptrace_request.patch
- recipes-overlayed/ltp/ltp/0024-rt_sigaction-rt_sigprocmark-Define-_GNU_SOURCE.patch
- recipes-overlayed/ltp/ltp/0025-mc_gethost-include-sys-types.h.patch
- recipes-overlayed/ltp/ltp/0026-crash01-Define-_GNU_SOURCE.patch
- recipes-overlayed/ltp/ltp/0027-sysconf01-Use-_SC_2_C_VERSION-conditionally.patch
- recipes-overlayed/ltp/ltp/0028-rt_sigaction.h-Use-sighandler_t-instead-of-__sighand.patch
- recipes-overlayed/ltp/ltp/0030-lib-Use-PTHREAD_MUTEX_RECURSIVE-in-place-of-PTHREAD_.patch
- recipes-overlayed/ltp/ltp/0033-shmat1-Cover-GNU-specific-code-under-__USE_GNU.patch
- recipes-overlayed/ltp/ltp/0034-periodic_output.patch
- recipes-overlayed/ltp/ltp/0035-fix-test_proc_kill-hang.patch
- recipes-overlayed/ltp/ltp/0036-testcases-network-nfsv4-acl-acl1.c-Security-fix-on-s.patch
- recipes-overlayed/ltp/ltp/0039-fcntl-fix-the-time-def-to-use-time_t.patch
- recipes-overlayed/ltp/ltp_20170116.bb
overlay LTP recipe on Morty to get latest 20170116 release.
> ltp: update to 20170116

- recipes-samples/images/rpb-minimal-image.bb
> rpb-minimal-image: add kernel-modules

- recipes-overlayed/kselftests/files/0001-selftests-breakpoints-allow-to-cross-compile-for-aar.patch
- recipes-overlayed/kselftests/files/0001-selftests-gpio-use-pkg-config.patch
- recipes-overlayed/kselftests/files/0001-selftests-lib-allow-to-override-CC-in-the-top-level-Makefile.patch
- recipes-overlayed/kselftests/files/0001-selftests-net-use-LDLIBS-to-link-against-libnuma.patch
- recipes-overlayed/kselftests/files/0001-selftests-seccomp-use-LDLIBS-to-link-against-libpthread.patch
- recipes-overlayed/kselftests/files/0001-selftests-sigaltstack-fix-packaging.patch
- recipes-overlayed/kselftests/files/0001-selftests-timers-use-LDLIBS-to-link-against-libpthread.patch
- recipes-overlayed/kselftests/kselftests_4.10.bb
> kselftests: update to 4.10

- conf/distro/include/rpb.inc
> rpb.inc: set SDK name and version

- conf/distro/include/rpb.inc
> rpb.inc: fix multilib enablement

- conf/distro/include/rpb.inc
> rpb: make DISTRO_VERSION match with upcoming Yocto Project release.

- conf/distro/include/rpb.inc
> make DISTRO_VERSION match with 'morty' Yocto Project release.

- recipes-samples/packagegroups/packagegroup-rpb-weston.bb
> packagegroups: add Chromium and ChromeDriver to Weston package group

- recipes-samples/packagegroups/packagegroup-rpb-weston.bb
> [pyro] packagegroups: add Chromium and ChromeDriver to Weston package group

- classes/lkft-metadata.bbclass
Add class to write out SRC_URI for lkft and enable it
> Lkft metadata

- conf/distro/include/rpb.inc
>  Move to gcc 7

- recipes-samples/packagegroups/packagegroup-rpb-tests.bb
> packagegroup-rpb-tests: add ALSA speaker-test

- recipes-overlayed/kselftests/kselftests-common.inc
> kselftests-common: include src files to the -dbg package

- recipes-samples/packagegroups/packagegroup-rpb-x11.bb
The target has changed in meta-browser.
> Change chromium target to chromium-x11

- recipes-overlayed/ltp/ltp_git.bb
Set DEFAULT_PREFERENCE to -1 to keep using the released version by
default.
> ltp: add a recipe to track LTP master branch

- conf/distro/include/rpb.inc
> rpb.inc: force linaro-gcc 7.2

- recipes-overlayed/kselftests/kselftests-mainline_4.18.bb
- recipes-overlayed/kselftests/kselftests-next_git.bb
LKFT Linux changes due to 4.18 being released.
> lkft: Linux updates for 4.18

- conf/distro/include/rpb.inc
Will need to be backported to morty/sumo/etc
> Master no more multilib

- recipes-overlayed/kselftests/kselftests-next_git.bb
> kseftests-next: Update PV to 4.19

- conf/distro/include/rpb.inc
> rpb: set DISTRO_VERSION for thud

- conf/distro/rpb-sota.conf
Signed-off-by: vishal <vishal.bhoj@linaro.org>
> Add sota distro variant

- conf/layer.conf
Outcome of the new codename "warrior" update:
https://www.mail-archive.com/openembedded-core@lists.openembedded.org/msg121571.html
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
> layer.conf: update compat to warrior

- recipes-samples/images/rpb-minimal-image.bb
- recipes-samples/packagegroups/packagegroup-rpb-weston.bb
- recipes-samples/packagegroups/packagegroup-rpb-x11.bb
> recipes-samples: Update deprecated distro_features_check -> features_check

- recipes-samples/packagegroups/packagegroup-rpb.bb
This is very useful for any kind of audio bringup or debug work.
> packagegroup-rpb: include alsa amixer

- conf/layer.conf
> conf/layer.conf: Bump compat layer to dunfell

- conf/distro/include/rpb.inc
> Bump rpb dunfell version to 3.1

- recipes-samples/packagegroups/packagegroup-rpb-tests.bb
> packagegroup-rpb-test: add i2c-tools

- conf/layer.conf
> conf/layer.conf: Bump to gatesgarth

- recipes-samples/packagegroups/packagegroup-rpb-tests.bb
- recipes-samples/packagegroups/packagegroup-rpb-x11.bb
Add `alsaucm` to console tests and `vulkan-tools` to x11 packages.
> More test programs

- recipes-overlayed/feh/feh/fehbg
- recipes-overlayed/feh/feh/fehbg.desktop
- recipes-overlayed/feh/feh_%.bbappend
- recipes-overlayed/openbox/openbox/menu.xml
- recipes-overlayed/openbox/openbox_%.bbappend
- recipes-samples/artwork/96boards-artwork_git.bb
- recipes-samples/packagegroups/packagegroup-rpb-x11.bb
Provide sensible Openbox menu and use branded background for X11 session.
This depends on [the meta-oe patch series](https://lists.openembedded.org/g/openembedded-devel/message/88416)
> rpb-desktop-image usability improvements

- classes/image-adbd.bbclass
- recipes-samples/images/rpb-minimal-image.bb
> ADB daemon support

- classes/image-adbd.bbclass
- recipes-samples/images/rpb-minimal-image.bb
Dependencies:
https://review.linaro.org/c/openembedded/meta-backports/+/37709/1
https://review.linaro.org/c/openembedded/meta-backports/+/37708/1
https://review.linaro.org/c/openembedded/meta-backports/+/37707/1
> Adbd dunfell

- classes/image-adbd.bbclass
- conf/distro/include/distro-multilib.inc
- conf/distro/include/rpb.inc
- conf/distro/rpb-eglfs.conf
- conf/distro/rpb-wayland.conf
- conf/distro/rpb.conf
- conf/layer.conf
- recipes-overlayed/busybox/busybox_1.%.bbappend
- recipes-overlayed/feh/feh_%.bbappend
- recipes-overlayed/openbox/openbox_%.bbappend
- recipes-samples/artwork/96boards-artwork_git.bb
- recipes-samples/images/rpb-console-image.bb
- recipes-samples/initrdscripts/rpb-boot-initramfs_1.0.bb
- recipes-samples/packagegroups/packagegroup-rpb-tests-weston.bb
- recipes-samples/packagegroups/packagegroup-rpb-tests-x11.bb
- recipes-samples/packagegroups/packagegroup-rpb-tests.bb
- recipes-samples/packagegroups/packagegroup-rpb-weston.bb
- recipes-samples/packagegroups/packagegroup-rpb-x11.bb
- recipes-samples/packagegroups/packagegroup-rpb.bb
- switch to delcaring compatibility with `honister`
- convert overrides syntax
> Switch to the honister OE release

- recipes-samples/packagegroups/packagegroup-rpb-tests.bb
Add pm-qa test packages to packagegroup-rpb-tests.
> packagegroup-rpb-tests: Add pm-qa test package

- conf/distro/include/rpb.inc
meta-arm-toolchain updated provided toolchain to 11.2, follow this update.
> rpb.inc: update GCCVERSION to arm-11.2

- conf/distro/include/rpb.inc
meta-arm-toolchain updated provided toolchain to 11.3, follow this update.
> rpb.inc: update GCCVERSION to arm-11.3

- conf/distro/include/rpb.inc
meta-arm-toolchain updated provided toolchain to 12.2, follow this update.
> rpb.inc: update GCCVERSION to arm-12.2

- conf/layer.conf
Declare compatibility with new release branch, scarthgap
> layer.conf: declare compat with scarthgap

- conf/layer.conf
- recipes-overlayed/feh/feh_%.bbappend
- recipes-overlayed/openbox/openbox_%.bbappend
- recipes-samples/initrdscripts/rpb-boot-initramfs_1.0.bb
Adjust RPB recipes to follow the UNPACKDIR-related changes in OE-Core
> Follow UNPACKDIR introduction
