conf/distro/include/rpb.inc
Allow users to override the choice of compiler to use.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
=> distro/include/rpb.inc: allow GCCVERSION override

conf/distro/include/rpb.inc, recipes-samples/images/rpb-desktop-image.bb
* add gpsd in our reference images
* disable Qt support in gpsd by default in RPB distros, to avoid bringing Qt
(especially Qt4) into OE RBP.
=> rpb: add gpsd support

recipes-samples/images/rpb-desktop-image.bb
In oe-core/master:
ERROR: glmark2 was skipped: Recipe is blacklisted: BROKEN: fails to build with
gcc-6
We will add it back once the issue is fixed.
=> rpb-desktop-image: remove glmark2

conf/distro/include/arm-defaults.inc, conf/distro/include/rpb.inc
As a bonus this also fixes up anti-social BSPs that force cortex* tunes instead of armv7a ones.
=> rbp: force hardfloat abi for armv7a

conf/distro/include/rpb.inc
so that we can use it in RPB based builds.
=> rpb: whitelist gstreamer1.0-libav license flag

recipes-samples/images/rpb-desktop-image.bb, recipes-samples/images/rpb-weston-image.bb
The plugins are added only if the appropriate license is whitelisted in the
build environment.
=> rpb: add gstreamer1.0-libav in -desktop and -weston images

conf/distro/include/rpb.inc, conf/distro/rpb-wayland.conf
=> rpb: move mali magic to global distro, vanilla RPB fails to build without it

recipes-samples/images/rpb-desktop-image.bb
The default systemd target in our current build is multi-user.target, for the
desktop image we prefer to boot to graphical.target to get the 'desktop'.
=> rpd-desktop-image: make sure image is booted until desktop

recipes-samples/images/rpb-desktop-image-lava.bb
Add piglit into the image, in order to run piglit test suite in CI loop.
=> rpb-desktop-image-lava: add piglit test suite

conf/distro/include/rpb.inc
Instead of setting LICENSE_FLAGS_WHITELIST , let's append to the variable, in
case it is already set with some initial values in any of the local conf/*.conf
files (which are parsed before the $DISTRO .conf file).
=> rpb: append flags to LICENSE_FLAGS_WHITELIST

conf/distro/include/rpb.inc, conf/distro/rpb-eglfs.conf, recipes-samples/images/rpb-qt5-image.bb
This pull requests allows the generation of an image suitable for embedded systems not needing a window manager (x11 or Wayland).
It enables Qt5/eglfs (http://doc.qt.io/qt-5/embedded-linux.html) 
The user can validate the native window using Qt5_CinematicExperience as follows:
$ cd /usr/share/cinematicexperience-1.0/
$ ./Qt5_CinematicExperience --platform eglfs
This commit was tested for the db410c release:
IMAGES=rpb-qt5-image
DISTRO=rpb-qt5
=> rpb-qt: qt5/eglfs image (no window manager)

conf/distro/include/distro-multilib.inc, conf/distro/include/rpb.inc
For 32bit machines this change should be transparent, nothing will move. For 64bit machines libs will now be in lib64.
=> RPB: switch to multilib by default.

recipes-samples/images/rpb-console-image-lava.bb, recipes-samples/images/rpb-desktop-image-lava.bb, recipes-samples/images/rpb-weston-image-lava.bb
Instead of adding only the few modules we might need, let's add them all at
once. These images are test images anyways.
This change also fixes https://validation.linaro.org/scheduler/job/1301682, so
it looks like we were missing some Python features.
=> rpb-*-image-lava: be more conservative and add python-modules

conf/distro/include/rpb.inc
6.2 is the OE-core default, so let's match that
=> rpb: move to gcc linaro-6.2

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
We should not add test packages that depend on x11 unconditionally, it was
caught on CI like this:
07:35:30 Parsing of 2626 .bb files complete (0 cached, 2626 parsed). 6060 targets, 1302 skipped, 0 masked, 0 errors.
07:35:30 NOTE: Resolving any missing task queue dependencies
07:35:30 ERROR: Nothing RPROVIDES 'piglit' (but /srv/oe/build/conf/../../layers/meta-rpb/recipes-samples/packagegroups/packagegroup-rpb-tests.bb RDEPENDS on or otherwise requires it)
07:35:30 ERROR: piglit was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
=> packagegroup-rpb-tests: check for x11 in DISTRO_FEATURES

recipes-samples/images/rpb-console-image.bb, recipes-samples/images/rpb-desktop-image.bb, recipes-samples/images/rpb-weston-image.bb, recipes-samples/packagegroups/packagegroup-rpb.bb
To avoid duplication , let's organize our image using packagegroups. There
should be no change for -desktop and -weston images, but in the process we are
adding more packages to -console image (gps, gstreamer, ...) which are valid
packages even for headless images.
=> rpb*-image: create packagegroup to better organize images

conf/distro/include/distro-multilib.inc
32bit now goes into /lib32, 64bit into /lib. This is a workaround for the broken python3 recipe.
=> distro-multilib.inc: switch libdir naming

conf/distro/include/rpb.inc
Not all bugs are fixed, but the main one (python3) is worked around, so reactivate multilib.
This reverts commit 309966ff6ce09b9455e09052d20ca90ee32b0cab.
=> Revert "rbp.inc: disable multilib till bugs are fixed"

recipes-samples/packagegroups/packagegroup-rpb-weston.bb, recipes-samples/packagegroups/packagegroup-rpb-x11.bb, recipes-samples/packagegroups/packagegroup-rpb.bb
Commit 92f304e9133 (rpb*-image: create packagegroup to better organize image)
introduced a regression, since
* packagegroup-rpb recipe is required for -console image, to all packages from
packagegroup-rpb-x11 are built as well, though they are not included in the
image.
* the commit also adds Gstreamer in the -console image. When building -console
with 'x11' enabled, it will bring a lot of X packages regardless of
packagegroup-rpb-x11
As such, we are now doing splitting the packagegroup recipes into multiple
recipes to avoid building packages not needed when building only -console
image, and we remove Gstreamer from -console for now.
=> packagegroup: split -rpb into multiple recipes

conf/distro/include/rpb.inc
This adds the fragment which is present in hikey and qcom-apq80xx.inc machine configs (in this exact form), but is missing from meta-ti's machine configs.
=> rpb.inc: add ext4.gz image

recipes-overlayed/efivar/efivar/0001-efivar-fix-for-cross-compile.patch, recipes-overlayed/efivar/efivar/0003-efivar-fix-for-cross-compile.patch, recipes-overlayed/efivar/efivar/allow-multi-definitions-for-native.patch, recipes-overlayed/efivar/efivar_0.30.bb
Efivar fails to build with a recent libc-headers, so overlay it till it gets accepted into meta-oe.
=> Overlay efivar

conf/distro/include/rpb.inc
We want to enable multilib only on 64bit machines. Get TUNE_FEATURES to
detect if it is an aarch64 machine and set the file to include accordingly.
We use a weak include (instead of require) to avoid to produce an error
when the file cannot be found.
=> rpb: enable multilib conditionally (only for aarch64)

conf/distro/include/rpb.inc
Meta-linaro-toolchain switched to 6.3, so fix the '6.2 is missing' errors and try to future proof it a bit.
=> rpb.inc: change GCCVERSION for linaro-6.%

recipes-samples/packagegroups/packagegroup-rpb.bb
While docker can run on arm 32bit, we prefer to focus on arm 64bit
devices. If some users express interest in having docker on arm 32bit, we
can revisit.
=> packagegroup-rpb: remove docker from armv7a hardware

conf/distro/rpb-eglfs.conf
bugfix for "EGL_EXT_device_base missing"
gbm is needed for the creation of  the  libqeglfs-kms-integration.so plugin
=> eglfs with Qt5.8: add gbm to PACKAGECONFIG

conf/distro/include/rpb.inc
It isn't currently supported. You should use default toolchain.
If you use the external toolchain support, multilib is disabled.
=> rpb: disable multilib when using external toolchain

conf/distro/include/distro-multilib.inc
The Yocto Project docs keep using tune-foo, which doesn't work, so fall back to something that does work.
=> distro-multilib.inc: fix libdir for armv8

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
I haven't found where it is used in LAVA, test-runner or QA test
definitions, so remove it for now. We'll re-add if it's really required.
=> packagegroup-rpb-tests: remove python-scons

conf/distro/include/rpb.inc, recipes-samples/images/rpb-console-image.bb
Attempt to reduce the images size by removing unnecessary packages like ofono, lxc and their dependencies.
=> Fine tune packages installed by default

conf/distro/include/rpb.inc
Let the user define that as a build-system option instead of forcing as
a default distro option.
Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>
=> rpb.inc: remove rm_work by default

conf/distro/include/rpb.inc
This will enable kmssink which can be used for rendering video without X11 , nor
wayland.
=> rpb: enable kms in gstreamer -bad plugins set

conf/distro/include/distro-multilib.inc, recipes-samples/images/rpb-multilib-image.bb
Opkg can't do file-level conflict resolution for multilib, so switch to RPM.
=> distro-multilib.inc: enfore RPM as package format

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
For some LAVA tests, such as the ui-browser-test, which
require installing software via pip, this is about enough to
get everything in working order.
=> tests: add python-pip

conf/distro/include/distro-multilib.inc
Both '/lib' and '/lib64' are builtin defaults for gcc, 'lib32' isn't. Some recipes (e.g. shadow) will fail to build when using non-builtin paths.
Another problem is that the '/lib' assignment here was partially overriden to '/lib64' by OE-core, so comment that assignment as well.
=> distro-multilib: switch around lib/lib{32,64} again

recipes-samples/packagegroups/packagegroup-rpb.bb
The current approach prevents to use:
RDEPENDS_packagegroup-rpb_remove = "docker"
It's causing the following error:
Computing transaction...error: Can't install packagegroup-rpb-1.0-r0@all:
no package provides docker
Use bitbake's utils.contains function to filter out docker, instead of the
current approach and allow to use RDEPENDS_packagegroup-rpb.
=> packagegroup-rpb: use bb.utils.contains to filter out docker

recipes-samples/packagegroups/packagegroup-rpb-weston.bb, recipes-samples/packagegroups/packagegroup-rpb-x11.bb
kmscube is a very convenient graphic test app, and it is always useful to have
it handy. Adding kmscube in packagegroup-rpb instead would bring mesa and
gstreamer in the headless console image which is probably not a good idea. so
adding it in the graphical images only.
=> packagegroup-rpb-{x11,weston}: add kmscube

recipes-devtools/python/python-pexpect_4.2.1.bb, recipes-devtools/python/python-ptyprocess_0.5.1.bb
OE-core rev 701ac8e558c9c09cdab2306ebc416f0070585b11 removed the recipe, but we still depend on it, so import it.
=> python-pexpect: import from OE-core

recipes-overlayed/kselftests/0001-selftests-Fix-installation-for-splice-test.patch
This patch is expected to be merged upstream, as it has
reached the maintainer's next branch.
=> kselftests: update splice test patch

recipes-overlayed/kselftests/kselftests-common.inc, recipes-overlayed/kselftests/kselftests-mainline_4.12.bb, recipes-overlayed/kselftests/kselftests-next_git.bb
Since they share common bits to compile/install, add an include to carry
the common code.
=> kselftests: add recipes for mainline and linux-kselftest next branch

conf/distro/include/rpb.inc
By default, meta-ti and TI SDK ship tar.xz rootfs tarball for SD card
deployment. fastboot is preferred for deployment in automation.
Ensure we generate ext4.gz image for omap-15 family (like Beagle x15), so
we can flash sparse images with fastboot.
Due to the order of the includes, set this configuration in DISTRO.conf.
Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>
=> rpb.inc: ensure ext4.gz rootfs is generated for omap-15 family

conf/distro/include/rpb.inc
The next oe-core (rocko) release is using gcc 7.X realese.
Tested building rpb-minimal-image for db410c.
=> conf/distro: Set GCCVERSION to use gcc 7.1 from Linaro

conf/distro/include/rpb.inc, recipes-samples/packagegroups/packagegroup-rpb-x11.bb
Now that we have v4l2 codecs support in ffmpeg, let's add it into the image, by
default.
ffplay is a nice utility to play video using ffmpeg, but it requires sdl2
support, so let's add that too.
=> rpb: add ffmpeg (and ffplay)

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
When running tests plans with test-runner some tests requires
to have free space, so add 1 GB for now to avoid Out of space
problems.
=> packagegroup-rpb-tests: add stress-ng on console tests

recipes-samples/images/rpb-console-image-lava.bb, recipes-samples/images/rpb-desktop-image-lava.bb, recipes-samples/images/rpb-weston-image-lava.bb
LAVA copies the test overlay before boot and the image ran out
of space during this process [1].
The lava-dispatcher logic copies the test scripts and cases inside
rootfs before boot mounting the rootfs partition. I tested this changes
see apply-overlay-sparse-image in [2].
[1] https://staging.validation.linaro.org/scheduler/job/194060
[2] https://staging.validation.linaro.org/scheduler/job/194183
=> recipes-samples/images: RPB Lava images adds 32MB extra space

recipes-samples/images/rpb-console-image-lava.bb, recipes-samples/images/rpb-desktop-image-lava.bb, recipes-samples/images/rpb-weston-image-lava.bb
LAVA copies the test overlay before boot and the image ran out
of space during this process [1].
The lava-dispatcher logic copies the test scripts and cases inside
rootfs before boot mounting the rootfs partition. I tested this changes
see apply-overlay-sparse-image in [2].
[1] https://staging.validation.linaro.org/scheduler/job/194060
[2] https://staging.validation.linaro.org/scheduler/job/194183
=> recipes-samples/images: RPB Lava images adds 32MB of extra space

recipes-samples/images/rpb-console-image-lava.bb, recipes-samples/images/rpb-desktop-image-lava.bb, recipes-samples/images/rpb-weston-image-lava.bb
The space ran out when we added other smoke tests WLAN/HCI [1],
after review the actual size of test overlay in lt-qcom build is
358M [2].
The reason is because LAVA copies the test definition repository for
every entry in test, the actual size of the test-definitions repository
is around 25M, and we have currently 14 tests declared.
LAVA needs to improve the way to handle the same repository with
different tests (symlinks) or providing support to test plans.
[1] https://staging.validation.linaro.org/scheduler/job/195319
[2]
https://staging.validation.linaro.org/scheduler/job/195319/definition#defline89
=> images/rpb-*-lava: Increase the extra size to 1GB

conf/distro/include/rpb.inc, recipes-samples/images/rpb-console-image-lava.bb, recipes-samples/images/rpb-desktop-image-lava.bb, recipes-samples/images/rpb-weston-image-lava.bb, recipes-samples/packagegroups/packagegroup-rpb-tests.bb
The package test (ptest) enables support to run unittests
of packages into the DUT.
The rpb distro now enables to build ptest packages via
DISTRO_FEATURE ptest, this will cause to build ptest
packages in recipes that have support. [1]
In -lava images the ptest-runner and the ptests packages
are installed by default.
[1] https://wiki.yoctoproject.org/wiki/Ptest
=> rpb: Add support for ptest in -lava images

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
The Python3 intepreter is already installed (via bluez dep) in the
image but without python3-misc and python3-modules, isn't usable.
=> packagegroup-rpb-tests: Add python3-misc and python3-modules

recipes-samples/packagegroups/packagegroup-rpb-weston.bb
ffmpeg and ffplay have been recently added to packagegroup-rpb-x11. They
are worth adding to the weston images as well.
Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>
=> packagegroup-rpb-weston: add ffmpeg (and ffplay)

recipes-overlayed/kselftests/files/0002-selftests-seccomp-use-LDLIBS-instead-of-LDFLAGS.patch, recipes-overlayed/kselftests/files/0003-selftests-timers-use-LDLIBS-instead-of-LDFLAGS.patch, recipes-overlayed/kselftests/kselftests-mainline_4.14.bb
* Update md5sum/sha256sum for 4.14 tarball
* Drop patches merged upstream:
- 0001-selftests-breakpoints-re-order-TEST_GEN_PROGS-target.patc
- 0001-selftests-splice-fix-installation-for-splice-test.patch
* Refresh patches:
- 0002-selftests-seccomp-use-LDLIBS-instead-of-LDFLAGS.patch
- 0003-selftests-timers-use-LDLIBS-instead-of-LDFLAGS.patch
=> kselftests: upgrade to 4.14

recipes-overlayed/kselftests/kselftests-next_git.bb
=> kseftests-next_git: update PV to 4.14

recipes-overlayed/kselftests/files/0001-x86-ldt-Prevent-LDT-inheritance-on-exec.patch, recipes-overlayed/kselftests/kselftests-mainline_4.14.bb
This patch landed in to stable-rc-4.14 but the kselftest we are using is missing
this patch so adding this now as an extra patch.
NOTE: This patch would be removed when we upgrade kselftest to 4.15 mainline
Ref:
Thomas Gleixner <tglx@linutronix.de>
x86/ldt: Prevent LDT inheritance on exec
The bug we have is due to old test case code vs latest kernel source code.
kselftests: ldt_gdt_64 fails on x86
https://bugs.linaro.org/show_bug.cgi?id=3564
Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>
=> kselftests-mainline_4.14: Adding missing kselftest test patch

recipes-overlayed/kselftests/kselftests-common.inc
test intel_pstate uses cpupower, add that to RDEPEND
cd /opt/kselftests/default-in-kernel/intel_pstate
./run.sh
./run.sh: line 79: cpupower: command not found
=> kselftests-common: RDEPEND cpupower

recipes-overlayed/kselftests/kselftests-common.inc
Fix bpf/ tests:
libbpf: failed to open ./test_pkt_access.o: No such file or directory
libbpf: failed to open ./test_xdp.o: No such file or directory
libbpf: failed to open ./test_l4lb.o: No such file or directory
libbpf: failed to open ./test_tcp_estats.o: No such file or directory
test_tcp_estats:FAIL: err -2 errno 2
test_bpf_obj_id:PASS:get-fd-by-notexist-prog-id 0 nsec
test_bpf_obj_id:PASS:get-fd-by-notexist-map-id 0 nsec
libbpf: failed to open ./test_obj_id.o: No such file or directory
test_progs: test_progs.c:317: test_bpf_obj_id: Assertion `!err' failed.
Aborted (core dumped)
=> kselftests-common.inc: add bpf/*.o files into FILES_${PN}

recipes-overlayed/busybox/busybox_1.%.bbappend, recipes-overlayed/busybox/files/enable-setsid-tty.cfg
Using linaro-image-minimal-initramfs fails at init (kernel panic)
because setsid isn't available,
...
/init: line 41: setsid: command not found
[    2.769969] Kernel panic - not syncing: Attempted to kill init!
exitcode=0x00007f00
...
A previous discussion was made to enable conditionally via
DISTRO_FEATURES [1] but the patch wasn't integrated because the common
way is to use a bbappend.
This will enable setsid on all busybox builds that includes meta-rpb
layer, the size of the busybox build will increase ~2000 bytes.
[1] https://patchwork.openembedded.org/patch/29813/
=> recipes-overlayed: Add busybox bbappend to enable setsid

recipes-overlayed/kselftests/kselftests-next_git.bb
=> kseftests-next_git: update PV to 4.15

recipes-samples/packagegroups/packagegroup-rpb-tests-x11.bb
The gst-validate serves to test gstreamer components and it
needs xvfb to run without display attached.
=> packagegroup-rpb-tests-x11: Add gst-validate and xvfb

recipes-overlayed/kselftests/kselftests-common.inc
This adds cpupower to x86_64 kselftests builds, building
upon c1681a8, and fixes the inclusion for x86.
=> kselftests-common: fix RDEPENDS on cpupower

recipes-samples/images/rpb-initramfs-image-test.bb, recipes-samples/images/rpb-initramfs-image.bb, recipes-samples/initrdscripts/files/init.sh, recipes-samples/initrdscripts/rpb-boot-initramfs_1.0.bb
In order to provide support of ramdisk images to make kernel testing.
This recipes are heavily based on meta-initramfs (initramfs-debug{,image}
[1][2], add our own to don't depend on meta-initramfs layer and to make
customizations easily (changed the init (/ -> /sbin).
The LAVA image only contains stress-ng for now, later we will add simple
tools to test the kernel.
[1] http://layers.openembedded.org/layerindex/recipe/33578/
[2] http://layers.openembedded.org/layerindex/recipe/33579/
=> recipes-samples: Add rpb-initramfs-image{,-test}

recipes-samples/images/rpb-console-image-lkft.bb, recipes-samples/packagegroups/packagegroup-rpb-lkft.bb, recipes-samples/packagegroups/packagegroup-rpb-tests.bb
The LKFT image is close to the LAVA image with 2 main differences:
* ptest isn't enabled in the image features
* contains additional packages provided by the LKFT package group
=> recipe-samples: add a packagegroup and an image for LKFT

recipes-overlayed/chromium/files/0001-memcpy-used-without-including-string.h.patch
The below patch has been merged upstream, and is already present in
chromium-ozone-wayland_65.0.3315.0.
But chromium-x11_64.0.3282.167 recipe still needs it.
Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>
=> chromium-x11: put the missing patch back

conf/distro/include/rpb.inc
This gets rid of a warning during the parsing stage.
=> rpb.inc: set PREFERRED_PROVIDER for iasl

recipes-overlayed/busybox/busybox_1.%.bbappend, recipes-overlayed/busybox/files/enable-install.cfg, recipes-samples/images/rpb-initramfs-image-test.bb, recipes-samples/images/rpb-initramfs-image.bb, recipes-samples/initrdscripts/files/init.sh
The udev support is needed for some tests [1] also is good to have
automatic device node handling.
Add debugfs, devpts and tmpfs filesystems based on [2].
[1] https://github.com/andersson/bootrr
[2]
https://github.com/andersson/meta-stuff/blob/master/recipes-bsp/initrdscripts/files/init-debug.sh
=> rpb-initramfs-image-test: Changes to make image suitable for boot regression testing

recipes-samples/packagegroups/packagegroup-rpb-weston.bb, recipes-samples/packagegroups/packagegroup-rpb.bb
packagegroup are most of the time (and by default) arch:all, however in this
specific case, we have dependencies on MACHINE features, so that makes the
packages MACHINE_ARCH. While it does not 'fix' any build issue, it helps the
package feed and sstate.
=> packagegroup: some packagegroups are MACHINE_ARCH

recipes-samples/packagegroups/packagegroup-rpb-weston.bb, recipes-samples/packagegroups/packagegroup-rpb.bb
Fixes,
ERROR: Please ensure recipe
/srv/oe/build/conf/../../layers/meta-rpb/recipes-samples/packagegroups/packagegroup-rpb.bb
sets PACKAGE_ARCH before inherit packagegroup
In,
https://ci.linaro.org/job/lt-qcom-openembedded-rpb-rocko/DISTRO=rpb,MACHINE=dragonboard-410c,label=docker-stretch-amd64/95/console
=> recipes-samples/packagegroups: Fixes order to set PACKAGE_ARCH

recipes-overlayed/kselftests/kselftests-common.inc
Some Python3 modules needed for tests here (LAVA ptest) and there (kselftests' BPF).
These two commits can be shared with Rocko.
=> Add Python3 modules for tests

recipes-overlayed/clang/clang_git.bbappend, recipes-overlayed/kselftests/kselftests-common.inc
Some .o files needed by the bpf selftests were not being
produced because version 3.7+ of Clang was needed, with
support for the BPF target.
=> kselftests: depend on clang-native for BPF target

recipes-overlayed/clang/clang_git.bbappend
This reverts commit c888d0084072da5f5881ca14e1a4ef5f57e4dcca,
since the changes have now been appliend to upstream
meta-clang:
https://github.com/kraj/meta-clang/commit/63cdfebb47be639e3aff22f3592c238f3c3b495c
=> Revert "clang: enable support for BPF target"

recipes-overlayed/kselftests/files/0001-selftests-net-use-LDLIBS-instead-of-LDFLAGS-next-20180416.patch, recipes-overlayed/kselftests/kselftests-next_git.bb
Commit 192dc405f in linux-next/master added program tcp_mmap,
which required an updated patch for the LDFLAGS/LDLIBS
changes.
=> kselftests-next: refresh net/Makefile patch for LDLIBS

recipes-overlayed/kselftests/kselftests-mainline_4.16.bb
=> kselftests-mainline: upgrade to 4.16

recipes-overlayed/clang/clang_git.bbappend
This reverts commit d6a35dd84be434af104b579a9e8481a6cae12bc9,
since the changes have now been appliend to upstream
meta-clang:
https://github.com/kraj/meta-clang/commit/0f8dc80ce0dcb74bcb745aa7169b2e04a0f3fba9
=> [morty] Revert "clang: enable support for BPF target"

recipes-overlayed/kselftests/kselftests-common.inc
Clang does not know much about sysroot, so help here by passing the --sysroot switch via the CLANG environment variable. Also, some headers are needed in order to build some kselftests (at least bpf), so better make that dependency explicit.
=> Kselftests fixes wrt sysroot and headers

recipes-overlayed/kselftests/kselftests-common.inc
tc is needed by bpf/test_xdp_redirect.sh
=> kselftests: add tool tc

recipes-overlayed/kselftests/kselftests-common.inc
Kselftests net/rtnetlink.sh fails due to uuidgen isn't installed into
the rootfs:
./rtnetlink.sh: line 280: uuidgen: command not found
=> selftests: add uuidgen to RDEPENDS

recipes-overlayed/kselftests/kselftests-next_git.bb
It may happen that if a version is set for a kernel (not from linux-next), the fetcher will be unable to find the specified revision in the tree. Exempli gratia:
If `SRCREV_kernel` is set to `0f105cf4f60e5afdf2932fed7f05ce776ce14289` globally, (which is a fine kernel for torvalds/master, mainline), then this package would try to fetch the very same revision but from linux-next/master:
```
WARNING: kselftests-next-4.15+gitAUTOINC+0f105cf4f6-r0 do_fetch: Failed to fetch URL git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git;protocol=https;branch=master;name=kernel, attempting MIRRORS if available
ERROR: kselftests-next-4.15+gitAUTOINC+0f105cf4f6-r0 do_fetch: Fetcher failure: Unable to find revision 0f105cf4f60e5afdf2932fed7f05ce776ce14289 in branch master even from upstream …
```
=> kselftests-next: rename Git repository to kernel-next

recipes-overlayed/kselftests/kselftests-mainline_4.17.bb, recipes-overlayed/kselftests/kselftests-next_git.bb
Update PV of kselftests-mainline and in kselftests-next.
=> kselftests-mainline/-next: upgrade to 4.17

recipes-samples/packagegroups/packagegroup-rpb-tests-weston.bb
packagegroup-rpb-tests-weston includes test apps which can be used
in Weston Desktop.
In order to run gst-validate test with MMWG OE Weston build, some packages are needed.
So, I created a packagesgroup to organize it.
=> Add packagegroup-rpb-tests-weston.bb

recipes-samples/images/rpb-console-image-lkft.bb, recipes-samples/packagegroups/packagegroup-rpb-lkft.bb
Add missing dependency:
* `tzdata`
Fix architecture check in order to include numactl, and reduce the min. extra available space in the root file system from 1 GB to 256 MB, in order to fit into X15 userdata partition.
=> lkft: Fixes and dependency

recipes-samples/packagegroups/packagegroup-rpb-lkft.bb
A couple of bugs are related to lack of entropy, which can
be very easily solved by having haveged running.
HAVEGE algorithm explained here:
http://www.irisa.fr/caps/projects/hipsor/misc.php#exectime
regarding how randomness is obtained and about its
unpredictability. While rng-tools is the "preferred" method,
enough entropy might be very difficult in a headless
development board, where haveged would definitely be a great
addition.
=> packagegroup-rpb-lkft: add haveged

recipes-overlayed/kselftests/kselftests-common.inc
A lot of failures in BPF selftests are due to a missing
libelf.h, which is needed to construct libbpf.
=> kselftests: depend on elfutils (libelf.h)

recipes-overlayed/kselftests/kselftests-common.inc
In newer python3 argparse and subprocess have moved into python3-core.
=> kselftests-common: fix RDEPENDS for python3 packages

conf/distro/include/rpb.inc
Multilib creates more issues than is solves currently, e.g. LKFT runs into weird issues with headers. The original reason to enable it went away, so disable it.
=> [Sumo backport] rpb: disable multilib

recipes-overlayed/kselftests/files/0001-selftests-gpio-fix-build-error-next-20180906.patch, recipes-overlayed/kselftests/files/0001-selftests-gpio-use-pkg-config-to-determine-libmount-next-20180906.patch, recipes-overlayed/kselftests/files/0001-selftests-net-use-LDLIBS-instead-of-LDFLAGS-next-20180906.patch, recipes-overlayed/kselftests/kselftests-next_git.bb
As of next-20180906, a few Makefiles were slightly modified,
not much but enough to spoil the clean application of the
patches that we need.
=> kselftests-next: refresh net/gpio Makefile patches

recipes-overlayed/ltp/ltp_git.bb
As of commit 54d3e8696798, LTP has removed pounder21 stating
that "[i]t's is obsolete, not being built", so the recipe
fails trying to locate its license fail like this:
ERROR: ltp-20180118+gitAUTOINC+7599ff232b-r0 do_populate_lic: QA Issue: ltp:
LIC_FILES_CHKSUM points to an invalid file: /oe/build/tmp-rpb-glibc/work
/core2-32-linaro-linux/ltp/20180118+gitAUTOINC+7599ff232b-r0/git/tools
/pounder21/COPYING [license-checksum]
=> ltp: Remove license for pounder21, which has been removed

conf/layer.conf
Since sumo the LAYERSERIES_COMPAT flag is needed to ensure
layer compatibility so set to thud because will be the next
stable version now master.
=> conf/layer.conf: Add LAYERSERIES_COMPAT set to thud

recipes-overlayed/kselftests/files/0001-selftests-gpio-use-pkg-config-to-determine-libmount-next-20181008.patch, recipes-overlayed/kselftests/kselftests-next_git.bb
As of next-20181008, the GPIO Makefile was updated, thus
requiring only one patch, which had to be refreshed:
* 0001-selftests-gpio-fix-build-error: not needed anymore
* 0001-selftests-gpio-use-pkg-config-to-determine-libmount: updated
=> kselftests-next: Refresh gpio Makefile patch

recipes-overlayed/kselftests/kselftests-common.inc
ping6 is used by net's pmtu.sh test:
https://bugs.linaro.org/show_bug.cgi?id=3830
Busybox' ping6 is not good for this test as it doesn't
implement the -i parameter.
=> kselftests: Add iputils-ping6 to RDEPENDS

recipes-samples/packagegroups/packagegroup-rpb-tests-x11.bb, recipes-samples/packagegroups/packagegroup-rpb-weston.bb, recipes-samples/packagegroups/packagegroup-rpb-x11.bb
Currently chromium build is failing on master, We maintain our own
recipe for chromium, remove it for now have succesful builds in desktop
and weston images.
https://ci.linaro.org/job/96boards-reference-platform-openembedded-master/763/DISTRO=rpb,MACHINE=dragonboard-820c,label=docker-stretch-amd64/console
https://ci.linaro.org/job/96boards-reference-platform-openembedded-master/763/DISTRO=rpb-wayland,MACHINE=dragonboard-820c,label=docker-stretch-amd64/console
=> recipes-samples/packagegroups: Remove chromium in RPB packagegroups

recipes-overlayed/kselftests/kselftests-common.inc
While ping is used by net's pmtu.sh test and it's worked
pretty well in the past, the most recent version of test
uses the -M parameter to adjust the PMTU settings, so it
makes sense to use a full-featured ping instead of the one
provided by Busybox.
Details and links can be found here:
https://bugs.linaro.org/show_bug.cgi?id=3830#c9
=> kselftests: Add iputils-ping to RDEPENDS

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
Enable s-suite, thats a storage I/O benchmark test suite.
=> packagegroups/packagegroup-rpb-tests: enable s-suite

recipes-overlayed/ltp/ltp_git.bb
Use HTTP rather than git protocol so that things Just Work t.m. even for people operating behind corporate proxies that only allow outbound HTTP(S) connections.
=> Add procotol=http to ltp SRC_URI

recipes-overlayed/kselftests/kselftests-common.inc
As of iputils 20161105, ping6 has been "folded" into ping.
=> kselftests: Drop iputils-ping6 from RDEPENDS

recipes-samples/packagegroups/packagegroup-rpb.bb
The v4l2-compliance tool is used to test video4linux devices, either
video, vbi, radio or swradio, both input and output. It attempts to
test almost all aspects of a V4L2 device and it covers almost all V4L2
ioctls. It has very good support for video capture and output, VBI
capture and output and (software) radio tuning and transmitting.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> packagegroup-rpb-tests: add v4l-utils package for v4l2-compliance

conf/distro/include/rpb.inc
Gcc 7.x is outdated nowadays and the Arm version of gcc 8.x can't build go, so use the upstream OE-core version
=> rpb.inc: Switch to OE-core gcc 8

conf/distro/include/rpb.inc, conf/distro/rpb-sota.conf
Add support of sota on Thud branch:
- report of work made on Sumo branch on Thud branch.
Cherry-pick of commit from Sumo branch: 
3fc09e6 Add sota distro variant
7ce19a6 rpb: declare OSTREE_INITRAMFS_FSTYPES to stop parse failures with meta-updater included
=> Support of sota on THUD branch

conf/distro/include/arm-defaults.inc
Without this meta-browser will break parsing because it wants -march in
TUNE_CCARGS, but tune-cortexa*.inc only have -mtune.
Also merge in fixes from Angstrom to further collapse tunings to a
common vfp one.
=> arm-defaults.inc: also fix cortexa* tune files

conf/distro/include/rpb.inc
The correct version for Sumo is 2.5.
=> distro: Correct version for Sumo

recipes-samples/packagegroups/packagegroup-rpb.bb
There exist BSP layers which provide their own variants of optee, and
the package names are different. To account for that, introduce new
OPTEE_PACKAGES variable, initialize it to "optee-test  optee-client",
and make it overridable.
Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>
=> packagegroup-rpb: make it possible to override optee packages names

conf/distro/include/rpb.inc
ARM gcc 8.2 recipe is now merged on meta-linaro repository. 
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
=> rpb.inc: Switch to ARM gcc 8.2 toolchain

conf/distro/rpb-eglfs.conf, conf/distro/rpb-wayland.conf, conf/layer.conf, recipes-overlayed/busybox/busybox_1.%.bbappend
With these changes I was able to run yocto-check-layer to pass compatibility tests. with the caveat that I needed to remove references to docker and meta-virtualization which are failing compliance.
=> Check layer

recipes-samples/packagegroups/packagegroup-rpb.bb
When things don't work, strace, ldd, file are very
useful to figure out what might be happening.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> packagegroup-rpb: add some useful dev utilities

recipes-samples/packagegroups/packagegroup-rpb-tests.bb, recipes-samples/packagegroups/packagegroup-rpb.bb
python2 is EOL, update to python3.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> packagegroup-rpb-tests: update to python3 packages

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
net-snmp is needed in igt Chamelium test for sending command to PDU
to power cycle Chamelium if it is unreachable.
Signed-off-by: Arthur <arthur.she@linaro.org>
=> packagegroup-rpb-tests: add net-snmp

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
The igt-gpu-tools recipe has been merged to OE-core [1].
We'd like to have it be included in packagegroup-rpb-tests.
[1] https://git.openembedded.org/openembedded-core/tree/meta/recipes-graphics/igt-gpu-tools?id=d98e9b3612ab2c03503843cb3ea77bec7811a1d4
Signed-off-by: Arthur She <arthur.she@linaro.org>
=> packagegroup-rpb-tests: add igt-gpu-tools-tests

conf/distro/include/rpb.inc
The igt-gpu-tools recipe has been merged to OE-core [1],
however, the Chamelium support is disabled by default [2].
This bbappend will enable Chamelium support.
[1] http://layers.openembedded.org/layerindex/recipe/132395/
[2] https://lists.openembedded.org/g/openembedded-core/message/139726?p=,,,20,0,0,0::relevance,,chamelium,20,2,0,74985512
Signed-off-by: Arthur She <arthur.she@linaro.org>
=> recipes-overlayed: Add igt-gpu-tools append to enable Chamelium

conf/distro/include/rpb.inc
Enable `vulkan` in `DISTRO_FEATURES` for all RPB distros.
=> rpb.inc: enable vulkan globally

recipes-samples/packagegroups/packagegroup-rpb-tests-x11.bb
To test freedreno graphics with deqp.
=> packagegroup-rpb-tests-x11: Add opengl-es-cts, parallel-deqp-runner

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
Enable two additional packages to assist in testing the hardware.
=> packagegroup-rpb-tests: add libdrm-tests and libgpiod-tools packages

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
igt-gpu-tools is not compatible with musl, disable corresponding dependency.
=> packagegroup-rpb-tests: disable igt-gpu-tools on musl

recipes-samples/packagegroups/packagegroup-rpb-tests-weston.bb, recipes-samples/packagegroups/packagegroup-rpb-tests-x11.bb
The gst-validate was deprecated now at gst-devtools see,
https://git.openembedded.org/openembedded-core/commit/?id=4af4c8d56da67545d2e5e1e2242ff6878b909e44
=> recipes-samples: Update gst-validate -> gst-devtools on pkggroups

recipes-samples/images/rpb-desktop-image.bb, recipes-samples/packagegroups/packagegroup-rpb-tests-x11.bb, recipes-samples/packagegroups/packagegroup-rpb-x11.bb
Enable several standard X11 programs usually found in most systems.
=> packagegroup-rpb-x11: enable standard X11 programs

conf/distro/include/rpb.inc
Since arm-9.2 toolchain was removed from meta-arm, switch to arm-10.2
toolchain
=> rpb.inc: switch GCCVERSION to "arm-10.2"

recipes-overlayed/feh/feh_%.bbappend
feh-autostart uses feh to set background, so add explicit dependency on
it.
=> feh: make feh-autostart depend on feh

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
They now live in meta-lkft's packagegroup.
=> [sumo] packagegroup-rpb-tests: Drop more LKFT testsuites and tools

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
The cpupower recipe compiles code inside work-shared of Linux kernel if
linux-dummy is selected as default provider this code is not available,
so not include it when linux-dummy is selected.
=> recipes-samples: packagegroup-rpb-tests conditional includes cpupower

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
Is not supported needs port to glibc 2.34+.
Fixes,
https://ci.linaro.org/job/lt-qcom-linux-testimages/MACHINE=qemuarm,label=docker-buster-amd64/885/console
=> packagegroup-rpb-tests: Remove libhugetlbfs-tests for now

conf/distro/include/rpb.inc
meta-arm has upgraded provided toolchain from 10.2 to 10.3. Update
GCCVERSION accordingly.
=> rpb.inc: switch GCCVERSION to 10.3

recipes-samples/artwork/96boards-artwork_git.bb
Specify default branch in SRC_URI to fix the following warning:
WARNING: URL: git://github.com/96boards/96boards-artwork;protocol=https does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.
=> 96boards-artwork: specify branch

recipes-samples/packagegroups/packagegroup-rpb.bb
Some boards doesn't has a battery to store the datetime so
add ntp to sync when connect to Internet.
=> recipes-samples/packagegroup-rpb.bb: Add ntp package

recipes-samples/packagegroups/packagegroup-rpb-tests.bb, recipes-samples/packagegroups/packagegroup-rpb-weston.bb, recipes-samples/packagegroups/packagegroup-rpb-x11.bb, recipes-samples/packagegroups/packagegroup-rpb.bb
Add gps related test packages (gps, gps-utils and ncurses)
to packagegroup-rpb-tests.
This allows a quick test of the gps interface (if available)
with the rpb test images.
=> packagegroup-rpb-tests: Add gps related test packages

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
Add pciutils (which provides lspci like commands) to
packagegroup-rpb-tests.
This allows a quick test of the PCIe interface(s)
(if available) with the rpb test images.
=> packagegroup-rpb{-tests}: Add pciutils test package

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
Add {c}make to packagegroup-rpb-tests.
=> packagegroup-rpb{-tests}: Add {c}make test package

recipes-samples/packagegroups/packagegroup-rpb-tests.bb
Add iperf3 and netperf test packages (which allow determining
performance figures for an ethernet interface) to
packagegroup-rpb-tests.
=> packagegroup-rpb{-tests}: Add iperf3 and netperf test packages

conf/distro/include/rpb.inc
This decouples build system from the host distribution. This would make
sharing sstate even more practical.
=> rpb.inc: enable uninative usage

recipes-samples/artwork/96boards-artwork_git.bb
Fix the following warning by OpenEmbedded QA:
WARNING: 96boards-artwork-0.0+gitAUTOINC+066d5b151c-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses GPLv2 [obsolete-license]
=> 96boards-artwork: use SPDX identifier for the license

conf/distro/include/rpb.inc
oe-core has added the '-fcanon-prefix-map' option to DEBUG_PREFIX_MAP. However this option is only supported since gcc-13, while RPB defaults to ARM gcc 12. Remove this option for now.
=> rpb.inc: remove -fcanon-prefix-map from DEBUG_PREFIX_MAP

conf/distro/include/rpb.inc
There is little point in using ARM toolchain, the main (FSF) is pretty good enough. Stop using the ARM toolchain and switch to the default so that we do not diverge from main OE/Yocto and (potentially) don't have to cope with toolchain/codegen bugs which are not present/tested/handled by the rest of the community.
=> rpb.inc: stop using ARM toolchain

recipes-samples/packagegroups/packagegroup-rpb-x11.bb
The xsetmode package was dropped from meta-oe, drop it here too.
=> packagegroup-rpb-x11: drop xsetmode

conf/distro/include/rpb.inc
Commit [fa8c59c](https://github.com/openembedded/openembedded-core/commit/802e853eeddf16d73db1900546cc5f045d1fb7ed) in openembedded-core makes usrmerge a requirement, in order to make sure it still builds with older releases set the INIT_MANAGER variable so the configuration is always done right from the defaultsetup.conf loaded after the distro conf.
Log of build failure:
ERROR: Nothing RPROVIDES 'udev' (...)
systemd RPROVIDES udev but was skipped: missing required distro feature 'usrmerge' (not in DISTRO_FEATURES)
eudev RPROVIDES udev but was skipped: conflicting distro feature 'systemd' (in DISTRO_FEATURES)
NOTE: Runtime target 'udev' is unbuildable, removing... 
Missing or unbuildable dependency chain was: ['udev']
=> distro: rpb: set INIT_MANAGER as systemd

recipes-overlayed/xserver-xorg/xserver-xorg_%.bbappend
XvFB is necessary for gst-validate, reenable it.
=> xserver-xorg: reenable xvfb

recipes-samples/packagegroups/packagegroup-rpb.bb
In the commit cc4ec43a2b65 ("go: Drop fork of unpack code, mandate GO_SRCURI_DESTSUFFIX") OE-Core has dropped custom do_unpack implementation in favour of forcing Go recipes to use destsuffix option in SRC_URI. While Bruce is struggling with getting the meta-virt to work in the changed environment ([1]), disable docker dependency for now.
[1] https://lists.yoctoproject.org/g/meta-virtualization/message/8769
=> packagegroup-rpb: drop docker for now

recipes-samples/images/rpb-minimal-image.bb
The `debug-tweaks` IMAGE_FEATURE has been dropped in favour of explicitly using corresponding features. Replace it with the suggested list of features.
=> rpb-minimal-image: replace debug-tweaks feature

recipes-samples/images/rpb-minimal-image.bb
Bring back the "enable-adbd" feature dropped in the last commit.
Fixes: ceaef9214090 ("rpb-minimal-image: replace debug-tweaks feature")
=> rpb-minimal-image: restore enable-adbd feature
